name: Lars Beck-Friis
favicon: null
layout_spectrum: 0.94284
typography_spectrum: 0.06641
title: Mitt smultronst√§lle i cyberspace
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
